# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd58422e3ed9702d232a07973c450f4cc24f3256859d351fc8afe4916771f1b94ac41f6271281486a3ae4c32bbb3e29720dbd2c3b510571cc402571834320df1

test:
  secret_key_base: 8d18f4b2b877431c94199cb7c1549f2e48e2038bd84801ccaabc2a3889f0ef3e3b73657aa00f0dcf2c6eb0fefc225c0649be4212f13c74de8e8d1b96515afb7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
